# Generated by Django 3.1.5 on 2021-01-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20210115_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='balance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wallet.balance'),
            preserve_default=False,
        ),
    ]
