# Generated by Django 3.1.5 on 2021-01-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_operation_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_sign',
            field=models.BooleanField(verbose_name='Increase'),
        ),
    ]
