# Generated by Django 3.1.5 on 2021-01-25 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200, verbose_name='Symbol')),
                ('name', models.CharField(max_length=200, verbose_name='Symbol')),
                ('last_sale', models.FloatField(blank=True, null=True, verbose_name='Last Sale')),
                ('net_change', models.FloatField(blank=True, null=True, verbose_name='Net Change')),
                ('relative_change', models.FloatField(blank=True, null=True, verbose_name='% Change')),
                ('market_cap', models.FloatField(blank=True, null=True, verbose_name='Market Cap')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('ipo_year', models.CharField(max_length=200, verbose_name='IPO Year')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='Volume')),
                ('sector', models.CharField(max_length=200, verbose_name='Industry')),
                ('industry', models.CharField(max_length=200, verbose_name='Symbol')),
            ],
        ),
        migrations.AddField(
            model_name='portofolio',
            name='api_key',
            field=models.CharField(default='a', max_length=200, verbose_name='Api Key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='initial_balance',
            field=models.FloatField(blank=True, null=True, verbose_name='Initial Balance'),
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='DateTime')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='Open')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='High')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='Low')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='Close')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='Volume')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.company')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('range_lower', models.DateTimeField(verbose_name='From')),
                ('range_upper', models.DateTimeField(verbose_name='Until')),
                ('min', models.FloatField(default=0, verbose_name='Minimum')),
                ('max', models.FloatField(default=0, verbose_name='Maximum')),
                ('Q1', models.FloatField(default=0, verbose_name='25 %')),
                ('Q2', models.FloatField(default=0, verbose_name='50 %')),
                ('Q3', models.FloatField(default=0, verbose_name='75 %')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='portofolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
    ]
