# Generated by Django 3.1.5 on 2021-01-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageName', models.CharField(max_length=200, verbose_name='Parameter Name')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingsParameter', models.CharField(max_length=200, verbose_name='Parameter Name')),
                ('settingsValue', models.CharField(max_length=512, verbose_name='Value')),
                ('settingsComment', models.TextField(verbose_name='Comment')),
                ('settingsIntValue', models.IntegerField(verbose_name='Integer Value')),
                ('settingsFloatValue', models.FloatField(verbose_name='Float Value')),
                ('settingsPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.settingspage')),
            ],
        ),
    ]
