# Generated by Django 3.1.5 on 2021-01-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20210116_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='settingsFloatValue',
            field=models.FloatField(blank=True, null=True, verbose_name='Float Value'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='settingsIntValue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Integer Value'),
        ),
    ]
