# Generated by Django 3.1.5 on 2021-01-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20210116_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='settingsType',
            field=models.IntegerField(default=1, verbose_name='ValueType'),
        ),
    ]
