# Generated by Django 3.1.5 on 2021-01-18 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_setting_settingstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingsParameter', models.CharField(max_length=200, verbose_name='Parameter Name')),
                ('settingsValue', models.CharField(blank=True, max_length=512, verbose_name='Value')),
                ('settingsComment', models.TextField(blank=True, verbose_name='Comment')),
                ('settingsIntValue', models.IntegerField(blank=True, null=True, verbose_name='Integer Value')),
                ('settingsFloatValue', models.FloatField(blank=True, null=True, verbose_name='Float Value')),
                ('settingsType', models.IntegerField(default=1, verbose_name='ValueType')),
                ('settingsPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.settingspage')),
            ],
        ),
    ]
