# Generated by Django 3.1.5 on 2021-01-26 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_auto_20210125_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='portofolio',
        ),
        migrations.AddField(
            model_name='company',
            name='bought',
            field=models.BooleanField(default=False, verbose_name='Bought'),
        ),
        migrations.AddField(
            model_name='company',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Favorite'),
        ),
        migrations.AddField(
            model_name='company',
            name='marked',
            field=models.BooleanField(default=False, verbose_name='Marked'),
        ),
        migrations.AddField(
            model_name='company',
            name='sell',
            field=models.BooleanField(default=True, verbose_name='Sell'),
        ),
        migrations.AddField(
            model_name='company',
            name='watched',
            field=models.BooleanField(default=False, verbose_name='Watched'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('price', models.FloatField(verbose_name='Price')),
                ('operation_sign', models.BooleanField(verbose_name='Increase')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.balance')),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.company'),
        ),
        migrations.AddField(
            model_name='balance',
            name='portofolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
    ]
