# Generated by Django 3.1.5 on 2021-01-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0004_auto_20210126_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='etf',
            field=models.BooleanField(blank=True, max_length=200, null=True, verbose_name='ETF'),
        ),
        migrations.AddField(
            model_name='company',
            name='market_category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Market Category'),
        ),
        migrations.AddField(
            model_name='company',
            name='symbol_cqs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CQS Symbol'),
        ),
        migrations.AddField(
            model_name='company',
            name='symbol_nasdaq',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NASDAQ Symbol'),
        ),
    ]
