# Generated by Django 3.1.5 on 2021-01-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0005_auto_20210126_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Name'),
        ),
    ]
